Notebook 02 : Data Cleaning
# Healthcare Readmission Analytics

In [1]:
# ============================================================
# Notebook 02 : Data Cleaning
# Healthcare Readmission Analytics
# Objectives
# ------------------------------------------------------------
# 1. Identify missing values
# 2. Replace invalid values
# 3. Remove unnecessary columns
# 4. Fix data types
# 5. Save cleaned dataset
# ============================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [2]:
# ============================================================
# Load Dataset
# ============================================================

df = pd.read_csv("../data/raw/diabetic_data.csv")

In [3]:
# ============================================================
# Dataset Overview Before Cleaning
# ============================================================

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.head()

Rows    : 101766
Columns : 50

   encounter_id  patient_nbr             race  gender      age weight  admission_type_id  discharge_disposition_id  admission_source_id  time_in_hospital payer_code         medical_specialty  num_lab_procedures  num_procedures  num_medications  number_outpatient  number_emergency  number_inpatient  diag_1  diag_2 diag_3  number_diagnoses max_glu_serum A1Cresult metformin repaglinide nateglinide chlorpropamide glimepiride acetohexamide glipizide glyburide tolbutamide pioglitazone rosiglitazone acarbose miglitol troglitazone tolazamide examide citoglipton insulin glyburide-metformin glipizide-metformin glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone change diabetesMed readmitted
0       2278392      8222157        Caucasian  Female   [0-10)      ?                  6                        25                    1                 1          ?  Pediatrics-Endocrinology                  41               0                1                  0                 0                 0  250.83       ?      ?                 1           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      No                  No                  No                       No                      No                     No     No          No         NO
1        149190     55629189        Caucasian  Female  [10-20)      ?                  1                         1                    7                 3          ?                         ?                  59               0               18                  0                 0                 0     276  250.01    255                 9           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      Up                  No                  No                       No                      No                     No     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?                  1                         1                    7                 2          ?                         ?                  11               5               13                  2                 0                 1     648     250    V27                 6           NaN       NaN        No          No          No             No          No            No    Steady        No          No           No            No       No       No           No         No      No          No      No                  No                  No                       No                      No                     No     No         Yes         NO
3        500364     82442376        Caucasian    Male  [30-40)      ?                  1                         1                    7                 2          ?                         ?                  44               1               16                  0                 0                 0       8  250.43    403                 7           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      Up                  No                  No                       No                      No                     No     Ch         Yes         NO
4         16680     42519267        Caucasian    Male  [40-50)      ?                  1                         1                    7                 1          ?                         ?                  51               0                8                  0                 0                 0     197     157    250                 5           NaN       NaN        No          No          No             No          No            No    Steady        No          No           No            No       No       No           No         No      No          No  Steady                  No                  No                       No                      No                     No     Ch         Yes         NO

In [4]:
# ============================================================
# Replace Invalid Missing Values
# ============================================================

df.replace("?", np.nan, inplace=True)

        encounter_id  patient_nbr             race  gender      age weight  admission_type_id  discharge_disposition_id  admission_source_id  time_in_hospital payer_code         medical_specialty  num_lab_procedures  num_procedures  num_medications  number_outpatient  number_emergency  number_inpatient  diag_1  diag_2 diag_3  number_diagnoses max_glu_serum A1Cresult metformin repaglinide nateglinide chlorpropamide glimepiride acetohexamide glipizide glyburide tolbutamide pioglitazone rosiglitazone acarbose miglitol troglitazone tolazamide examide citoglipton insulin glyburide-metformin glipizide-metformin glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone change diabetesMed readmitted
0            2278392      8222157        Caucasian  Female   [0-10)    NaN                  6                        25                    1                 1        NaN  Pediatrics-Endocrinology                  41               0                1                  0                 0                 0  250.83     NaN    NaN                 1           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      No                  No                  No                       No                      No                     No     No          No         NO
1             149190     55629189        Caucasian  Female  [10-20)    NaN                  1                         1                    7                 3        NaN                       NaN                  59               0               18                  0                 0                 0     276  250.01    255                 9           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      Up                  No                  No                       No                      No                     No     Ch         Yes        >30
2              64410     86047875  AfricanAmerican  Female  [20-30)    NaN                  1                         1                    7                 2        NaN                       NaN                  11               5               13                  2                 0                 1     648     250    V27                 6           NaN       NaN        No          No          No             No          No            No    Steady        No          No           No            No       No       No           No         No      No          No      No                  No                  No                       No                      No                     No     No         Yes         NO
3             500364     82442376        Caucasian    Male  [30-40)    NaN                  1                         1                    7                 2        NaN                       NaN                  44               1               16                  0                 0                 0       8  250.43    403                 7           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      Up                  No                  No                       No                      No                     No     Ch         Yes         NO
4              16680     42519267        Caucasian    Male  [40-50)    NaN                  1                         1                    7                 1        NaN                       NaN                  51               0                8                  0                 0                 0     197     157    250                 5           NaN       NaN        No          No          No             No          No            No    Steady        No          No           No            No       No       No           No         No      No          No  Steady                  No                  No                       No                      No                     No     Ch         Yes         NO
...              ...          ...              ...     ...      ...    ...                ...                       ...                  ...               ...        ...                       ...                 ...             ...              ...                ...               ...               ...     ...     ...    ...               ...           ...       ...       ...         ...         ...            ...         ...           ...       ...       ...         ...          ...           ...      ...      ...          ...        ...     ...         ...     ...                 ...                 ...                      ...                     ...                    ...    ...         ...        ...
101761     443847548    100162476  AfricanAmerican    Male  [70-80)    NaN                  1                         3                    7                 3         MC                       NaN                  51               0               16                  0                 0                 0  250.13     291    458                 9           NaN        >8    Steady          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No    Down                  No                  No                       No                      No                     No     Ch         Yes        >30
101762     443847782     74694222  AfricanAmerican  Female  [80-90)    NaN                  1                         4                    5                 5         MC                       NaN                  33               3               18                  0                 0                 1     560     276    787                 9           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No  Steady                  No                  No                       No                      No                     No     No         Yes         NO
101763     443854148     41088789        Caucasian    Male  [70-80)    NaN                  1                         1                    7                 1         MC                       NaN                  53               0                9                  1                 0                 0      38     590    296                13           NaN       NaN    Steady          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No    Down                  No                  No                       No                      No                     No     Ch         Yes         NO
101764     443857166     31693671        Caucasian  Female  [80-90)    NaN                  2                         3                    7                10         MC           Surgery-General                  45               2               21                  0                 0                 1     996     285    998                 9           NaN       NaN        No          No          No             No          No            No    Steady        No          No       Steady            No       No       No           No         No      No          No      Up                  No                  No                       No                      No                     No     Ch         Yes         NO
101765     443867222    175429310        Caucasian    Male  [70-80)    NaN                  1                         1                    7                 6        NaN                       NaN                  13               3                3                  0                 0                 0     530     530    787                 9           NaN       NaN        No          No          No             No          No            No        No        No          No           No            No       No       No           No         No      No          No      No                  No                  No                       No                      No                     No     No          No         NO

[101766 rows x 50 columns]

In [5]:
# ============================================================
# Missing Value Analysis
# ============================================================

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing = missing[missing["Missing Values"] > 0]

missing.sort_values(by="Percentage", ascending=False)

                   Missing Values  Percentage
weight                      98569       96.86
max_glu_serum               96420       94.75
A1Cresult                   84748       83.28
medical_specialty           49949       49.08
payer_code                  40256       39.56
race                         2273        2.23
diag_3                       1423        1.40
diag_2                        358        0.35
diag_1                         21        0.02

In [6]:
# ============================================================
# Drop Columns with Excessive Missing Values
# ============================================================

columns_to_drop = [
    "weight",
    "max_glu_serum",
    "A1Cresult",
    "medical_specialty",
    "payer_code"
]

df.drop(columns=columns_to_drop, inplace=True)

print("Columns dropped successfully.")
print(f"Remaining Columns : {df.shape[1]}")

Columns dropped successfully.
Remaining Columns : 45

In [7]:
# ============================================================
# Check Remaining Missing Values
# ============================================================

remaining_missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

remaining_missing = remaining_missing[
    remaining_missing["Missing Values"] > 0
]

remaining_missing

        Missing Values  Percentage
race              2273        2.23
diag_1              21        0.02
diag_2             358        0.35
diag_3            1423        1.40

In [8]:
# ============================================================
# Fill Remaining Missing Values
# ============================================================

columns_to_fill = ["race", "diag_1", "diag_2", "diag_3"]

for column in columns_to_fill:
    df[column] = df[column].fillna(df[column].mode()[0])

print("Remaining missing values filled successfully.")

Remaining missing values filled successfully.

In [9]:
# ============================================================
# Verify Missing Values
# ============================================================

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing = missing[missing["Missing Values"] > 0]

missing

Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []

In [10]:
# ============================================================
# Check Duplicate Records
# ============================================================

duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [11]:
# ============================================================
# Dataset Shape After Cleaning
# ============================================================

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 101766
Columns : 45

In [12]:
# ============================================================
# Save Clean Dataset
# ============================================================

df.to_csv("../data/processed/diabetic_data_clean.csv", index=False)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.

In [13]:
# ============================================================
# Data Cleaning Summary
# ============================================================

print("=" * 50)
print("DATA CLEANING SUMMARY")
print("=" * 50)

print(f"Original Rows      : 101766")
print(f"Remaining Rows     : {df.shape[0]}")

print()

print("Dropped Columns")
print("----------------")

for column in columns_to_drop:
    print(f"• {column}")

print()

print("Filled Missing Values")
print("----------------------")

for column in columns_to_fill:
    print(f"• {column}")

print()

print(f"Final Columns : {df.shape[1]}")

print()
print("Notebook 02 Completed Successfully")

==================================================
DATA CLEANING SUMMARY
==================================================
Original Rows      : 101766
Remaining Rows     : 101766

Dropped Columns
----------------
• weight
• max_glu_serum
• A1Cresult
• medical_specialty
• payer_code

Filled Missing Values
----------------------
• race
• diag_1
• diag_2
• diag_3

Final Columns : 45

Notebook 02 Completed Successfully

In [14]:
print(df.shape)
print(df.isnull().sum().sum())
print(df.duplicated().sum())

(101766, 45)
0
0