# Notebook 06 — Machine Learning Model Comparison

## Objective

The objective of this notebook is to compare multiple machine learning algorithms for predicting hospital readmission.

The following models will be evaluated:

- Logistic Regression
- Decision Tree
- Random Forest
- K-Nearest Neighbors (KNN)
- Gaussian Naive Bayes

Each model will be evaluated using:

- Accuracy
- Precision
- Recall
- F1-score

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/processed/engineered_data.csv")

print("Dataset Loaded Successfully")

print(df.shape)

df.head()

Dataset Loaded Successfully
(101766, 79)

,encounter_id,patient_nbr,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,insulin_No,insulin_Steady,insulin_Up,glyburide-metformin_No,glyburide-metformin_Steady,glyburide-metformin_Up,glipizide-metformin_Steady,glimepiride-pioglitazone_Steady,metformin-rosiglitazone_Steady,metformin-pioglitazone_Steady
0,2278392,8222157,-3.824600,6,25,1,-1.137649,-0.106517,-0.785398,-1.848268,...,1,0,0,1,0,0,0,0,0,0
1,149190,55629189,-3.197277,1,1,7,-0.467653,0.808384,-0.785398,0.243390,...,0,0,1,1,0,0,0,0,0,0
2,64410,86047875,-2.569954,1,1,7,-0.802651,-1.631351,2.145781,-0.371804,...,1,0,0,1,0,0,0,0,0,0
3,500364,82442376,-1.942632,1,1,7,-0.802651,0.045967,-0.199162,-0.002688,...,0,0,1,1,0,0,0,0,0,0
4,16680,42519267,-1.315309,1,1,7,-1.137649,0.401761,-0.785398,-0.986997,...,0,1,0,1,0,0,0,0,0,0

In [3]:
X = df.drop("readmitted", axis=1)

y = df["readmitted"]

print("Feature Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Shape : (101766, 78)
Target Shape : (101766,)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Shape :", X_train.shape)
print("Testing Shape :", X_test.shape)

Training Shape : (81412, 78)
Testing Shape : (20354, 78)

In [5]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("Feature Scaling Completed.")

Feature Scaling Completed.

In [6]:
results = pd.DataFrame(
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

results

Empty DataFrame
Columns: [Model, Accuracy, Precision, Recall, F1 Score]
Index: []